// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference = (s, t) => {
  // create a map to store letters in s
  let sMap = new Map();

  for (letter of s) {
    sMap.set(letter, (sMap.get(letter) || 0) + 1);
  }

  // go through t string and see if it is map
  // if letter is in map, decrement count in map
  // if letter is not in map then return that letter
  for (letter of t) {
    if (!sMap.has(letter) || sMap.get(letter) === 0) {
      return letter;
    } else {
      sMap.set(letter, sMap.get(letter) - 1);
    }
  }
};
